# route builds to Ubuntu 18.04 LTS, Bionic
dist: bionic

# only push requests to master
if:
  type = push

# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
  - 3.8

# what branches should be evaluated
branches:
  only:
    - master

# install dependencies
install:
  - pip3 install -r requirements.txt

# scripts to run for build
script:
  - pytest --cov=source/ tests/
  - pylint source/ tests/

# generate a coverage report to send back to the user
after_success:
  - codecov

